### ISSUE TITLE
Compilation error - undefined reference

### ISSUE THREAD

**Issue by rkotulla** [iraf-community/iraf#104]
Hi all,

I'm trying to install the latest release version on a new laptop (running a fresh install of opensuse leap 15.1), following closely the instructions from the INSTALL.md.

After running for a while, this is what it ends up with:

...
----------------------- XYACC --------------------------
+ cd xyacc
+ sh -x mkpkg.sh
+ set -e
+ gcc -c -g -Wall -O2 -I/opt/iraf/include y1.c y2.c y3.c y4.c
y2.c: In function ‘setup’:
y2.c:188:11: warning: variable ‘sym_prefix’ set but not used [-Wunused-but-set-variable]
     char *sym_prefix = "";
           ^~~~~~~~~~
y2.c: In function ‘cpyact’:
y2.c:1389:10: warning: variable ‘id_name’ set but not used [-Wunused-but-set-variable]
     char id_name[NAMESIZE + 1];
          ^~~~~~~
y2.c:1388:36: warning: variable ‘argument’ set but not used [-Wunused-but-set-variable]
     int brac, c, match, j, s, tok, argument;
                                    ^~~~~~~~
+ gcc y1.o y2.o y3.o y4.o /opt/iraf/unix/hlib/libboot.a /opt/iraf/lib/libsys.a /opt/iraf/lib/libvops.a /opt/iraf/unix/hlib/libos.a /opt/iraf/unix/bin.linux64/libf2c.a -lm -o xyacc.e
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /opt/iraf/lib/libvops.a(miipak32.o): in function `miipa2_':
/opt/iraf/sys/osb/miipak32.c:93: undefined reference to `achtxl_'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /opt/iraf/sys/osb/miipak32.c:90: undefined reference to `achtdl_'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /opt/iraf/sys/osb/miipak32.c:87: undefined reference to `achtrl_'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /opt/iraf/sys/osb/miipak32.c:84: undefined reference to `achtll_'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /opt/iraf/sys/osb/miipak32.c:81: undefined reference to `achtil_'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /opt/iraf/sys/osb/miipak32.c:78: undefined reference to `achtsl_'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /opt/iraf/sys/osb/miipak32.c:75: undefined reference to `achtcl_'
collect2: error: ld returned 1 exit status
make: *** [Makefile:19: sysgen] Error 1

(full build.log attached). 

I've tried both the release version (as tar.gz and zip file) and the latest master branch, all with the same outcome. 

Up until then, this is what I ran (all as root):
cd /opt
wget  ...zip
unzip v2.16.1+2018.11.01.zip
mv iraf-2.16.1-2018.11.01 iraf
cd iraf
./install
make linux64
export PATH=/opt/iraf/bin/:$PATH
make sysgen 2>&1 | tee build2.log

Any suggestions on what might have gone wrong? Weird enough, running 
nm /opt/iraf/lib/libvops.a | grep achtxl
finds a reference to the problematic function just fine...

Thanks

[build2.log](https://github.com/iraf-community/iraf/files/4612197/build2.log)

**Comment by olebole** [comment]
That looks like the `generic` command didn't work correctly. From your log:
```
generic -k        -t csilrdx acht.gx
generic -k -p ak/ -t csilrdx achtc.x achts.x achti.x achtl.x achtr.x achtd.x achtx.x
Cannot open input file 'achts.x'
Cannot open input file 'achti.x'
Cannot open input file 'achtl.x'
Cannot open input file 'achtr.x'
Cannot open input file 'achtd.x'
Cannot open input file 'achtx.x'
```
The second invocation of `generic` would take the files generated by the first, which were not generated.

The compilation of `generic` looks OK, so my question is whether you have another command `generic` somewhere in your path?

**Comment by rkotulla** [comment]
Hi Ole,

thanks for that pointer. At first there indeed was another generic in the path, but even after getting rid of that one things didn't look up. After some manual fiddling around I found out that the "generic" that got compiled along the rest compiled fine and ran fine without any parameters, but seg-faulted as soon as it got some parameters (running a backtrace using gdb revealed some memory access issue while generating output - let me know if this is something worth looking into or just a brain-fart of my compiler). 

As a workaround, I copied over the generic executable from my work-machine, and after some more hacking got it to stick around and not get overwritten when IRAF compiles. This then actually generated most of the files that were missing from the earlier run. However, even though the compilation ran to the very end it didn't generate any executable, again due to missing references in some of the IRAF libraries that go into making the executables - I've attached the new build.log below. 

Can you think of anything else to try to get these references resolved - the ones I checked all seem to be part of the _proto or vosproto libraries, are defined as _extern, but not defined anywhere else.

Thank you and vielen Dank!


[build4b.log](https://github.com/iraf-community/iraf/files/4625005/build4b.log)

**Comment by olebole** [comment]
Hi Ralf,
the`iee..` errors come from a missing processing of `sys/osb/ieee.gx` by generic; you should run it manually if you want to continue hacking.
I would however be more interested in getting the *generic* program fixed, and for this a detailed stacktract would be great.
Also, could you give me more information about your system? Specifically, which SUSE version is it, and did you install a custom gcc or binutils? It would help me a lot when I could reproduce this locally.
Cheers
Ole

**Comment by jo101aw** [comment]
Hi, again,

I don't know whether this matters, but both in Ralf's and in my log there is the warning

conflicts: 19 shift/reduce
fmtio/evexpr.x is out of date; rebuilding with XYACC:
!xyacc evexpr.y; mv -f ytab.x evexpr.x
"evexpr.y", line 119: warning: redeclaration of precedence of GT.

conflicts: 16 shift/reduce

Best, Jo

**Comment by olebole** [comment]
No, the cause is different: Newer "lex" parser generators default to use (on both usual Linuxes and MacOS)
```
extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext
```
which is also declared in https://github.com/iraf-community/iraf/blob/cbfb21562716ae045cde9c3ccc8ecc8e11e7238e/unix/boot/generic/generic.c#L21

The lex parser on SuSELeap however generates the following definition:
```
char yytext[YYLMAX];
char *yytext_ptr;
```
(where the latter is filled elsewhere). This means that basically the use of `yytext` in `generic.c` is wrong; it should be replaced by `yytext_ptr`, since this is the pointer to `yytext`, independent of its implementation.
For a local workaround, you can replace the `lex` in https://github.com/iraf-community/iraf/blob/cbfb21562716ae045cde9c3ccc8ecc8e11e7238e/unix/boot/generic/mkpkg.sh#L10

with `flex` on SuSE.

**Comment by jo101aw** [comment]
Ok, thanks a lot. Excellent Job! Best, Jo
