### ISSUE TITLE
Compilation with gcc10 (Arch): Need to add fcommon flag to CFLAGS 

### ISSUE THREAD

**Issue by JiahuiZhuo** [iraf-community/iraf#121]
For people are trying to compile iraf with gcc10 (default compiler for Arch):
Have to modify the "Makefile" adding fcommon flag to the CFLAGS
That will look like:
`export CFLAGS   = -g -Wall -O2 $(CARCH) -fcommon`
Then the compilation can be executed correctly

The reason for that is because GCC 10 defaults to -fno-common, you can see that:
https://gcc.gnu.org/gcc-10/porting_to.html

**Comment by olebole** [comment]
Thank you for the report! 

This specific problem is already fixed in #111. Could you try this one out? If it works for you, I would close this issue.

**Comment by JiahuiZhuo** [comment]
> Thank you for the report!
> 
> This specific problem is already fixed in #111. Could you try this one out? If it works for you, I would close this issue.


I had just tried the latest code and it works perfectly! The issue was only occurs on "Snapshot 2.16.1+2018.11.01" which is literally the latest release. 
Thanks you for the attention
![Screenshot from 2020-10-01 15-42-17](https://user-images.githubusercontent.com/30496480/94816927-c2d03900-03fc-11eb-8cb6-ab0066b428bb.png)

**Comment by olebole** [comment]
Great! Thanks for the verification. I will therefore close this (and maybe it would be useful to make a new release at some point).

**Comment by tomcass240** [comment]
typing export CFLAGS = -g -Wall -O2 $(CARCH) -fcommon as told in the original comment just produces a bunch of error messages.

**Comment by olebole** [comment]
Since this is already fixed in the last version, there is no need to adjust it again. 
If it doesn't work for you, please specify exactly what you did and what the error messages are (i.e. attach the build log).
