### ISSUE TITLE
Cannot open file - no images to combine

### ISSUE THREAD

**Issue by Jefi4084** [iraf-community/iraf#124]
Hello - I am running the command zerocombine Bias* in the directory which contains the Bias images, but I receive the error:

Warning: Cannot open file (/home/mydirectory/flarecam/flarecam.dat)
ERROR: No images to combine
  "pclip=pclip, grow=0)"
     line 47: ccdred$zerocombine.cl
     called as: `zerocombine (input=Bias*)'

However, /home/mydirectory/flarecam/flarecam.dat does not exist. My flarecam.dat file is in /data/mydirectory/flarecam/flarecam.dat. 

Also, the paths in ccdsetint.par and imdccdred.par are /data/jefi4084/flarecam/flarecam.dat , not /home/mydirectory/flarecam/flarecam.dat. So I'm not sure why Iraf is trying to go to this path.

**Comment by olebole** [comment]
As written in #122, it is not recommended to use IRAF when starting with image reduction. Did you try out the the "Astropy" affiliated Python package "ccdproc"?

**Comment by olebole** [comment]
Sorry, this still does not contain enough information to reproduce the problem, and I doubt that it is a bug in IRAF. If you need help in using IRAF, please ask on https://iraf.net, or on f.e. Stackoverflow. If this is really a bug, please make a complete bug report, including all information to reproduce the problem.
