### ISSUE TITLE
IRAF and Apple M1 processors

### ISSUE THREAD

**Issue by sastanford** [iraf-community/iraf#133]
Does IRAF work on the new Apple M1 machines?  I'm having problems getting the cl to start up with an "iraf27" environment created in astroconda on an M1 based MacBook Pro.

**Comment by olebole** [comment]
It does not work yet. I would need access to an M1 Mac (with the XCode command line tools installed) to make it working, and I would need to finally decide on the architecture name. See #131 for further info.

If you would give me a temporary account on your MacBook, I could try to sort it out.

**Comment by olebole** [comment]
I am closing this issue; for further discussion of the macOS ARM port, head over to #131.

**Comment by sastanford** [comment]
I saw your post back in May about getting IRAF to work on an Apple M1 machine.  Can you please point me to where to download the correct version of IRAF ?

Thanks,
Adam Stanford

**Comment by olebole** [comment]
The latest snapshot ([v2.16.1+2021.06.14](https://github.com/iraf-community/iraf/releases/tag/v2.16.1%2B2021.06.14)) has support for the arm64 processor on Mac.

**Comment by sastanford** [comment]
Thank you. 

Is there a special release of x11iraf for the Apple M1?   I’m getting an error when doing a make from the x11iraf-2.0-2020.06.15 tarball -

gterm.c:2971:6: error: implicit declaration of function 'createPixmap' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            createPixmap (obm, s_pixmap, nx, ny, 8, pixmap, NULL, 0, 0);
            ^
gterm.c:2971:6: note: did you mean 'XCreatePixmap'?
/usr/X11/include/X11/Xlib.h:1597:15: note: 'XCreatePixmap' declared here
extern Pixmap XCreatePixmap(
              ^

**Comment by olebole** [comment]
This problem should be fixed in the latest upload in the x11iraf git repository. Can you try this out?

**Comment by sastanford** [comment]
Thank you.

**Comment by sastanford** [comment]
Is this the latest version of x11iraf?  

https://github.com/iraf-community/x11iraf/releases/tag/v2.0+2020.06.15 <https://github.com/iraf-community/x11iraf/releases/tag/v2.0+2020.06.15>


This is the version I’ve downloaded (https://github.com/iraf-community/x11iraf/archive/refs/tags/v2.0+2020.06.15.tar.gz <https://github.com/iraf-community/x11iraf/archive/refs/tags/v2.0+2020.06.15.tar.gz>) and tried to install but still getting this error when doing the make:

gterm.c:2971:6: error: implicit declaration of function 'createPixmap' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            createPixmap (obm, s_pixmap, nx, ny, 8, pixmap, NULL, 0, 0);
            ^
gterm.c:2971:6: note: did you mean 'XCreatePixmap'?
/usr/X11/include/X11/Xlib.h:1597:15: note: 'XCreatePixmap' declared here
extern Pixmap XCreatePixmap(

**Comment by olebole** [comment]
This is not in the released version yet; you would need to take the version directly from git. A new version is in preparation.
