### ISSUE TITLE
multiple DATE mismatches in master

### ISSUE THREAD

**Issue by fakahle** [iraf-community/iraf#135]
Fresh install on Centos7 from branch master:

Editing an image header with iraf command hedit sets file creation date to a date 10 years ahead (in my case to Feb 2031). Same with the keywords DATE and IRAF-TLM (set to 2031-02-27T13:22:05).

timedatectl on system-level and IRAF commands date and time show correct values.

Reverting to iraf-2.16.1-2018.11.01 there is no such (mis)behavior and the dates are set to correct values.

Any idea how to fix this?
Frank

**Comment by olebole** [comment]
This seems to be a unwanted side effect of #118. I will revert the relevant change.
