### ISSUE TITLE
Arm Mac installation

### ISSUE THREAD

**Issue by karlglazebrook** [iraf-community/iraf#161]
Not so much an 'issue' - as it worked - but you kindly sent me the trick on twitter to build your branch on my M1 Mac and so I thought I would report back.

Commands

```
git clone https://github.com/olebole/iraf.git
cd iraf
git checkout macarm64
PATH=${HOME}/.iraf/bin:$PATH
./install
make macos64
make sysgen

```

It built and worked - quite impressive! I noticed a few warnings along the lines of 
`ld: warning: could not create compact unwind for _wfqsct_: registers 74 and 75 not saved contiguously in frame
`
In one of my other projects I found the solution to this was to use the` -Wl,-no_compact_unwind` flag - not that I know what it does!

**Comment by olebole** [comment]
Thank you for the report for #131! I also have no idea what the warning really means; for the moment I would just ignore it. 
As there were no problems, I am closing this.

**Comment by karlglazebrook** [comment]
You can just use

cc -Wl,-no_compact_unwind

It seems hard to find an explanation of it.


Karl

**Comment by olebole** [comment]
Since I don't whether this is a) a problem, and b) the `no_compact_unwind` option actually fixes something, I don't want to do this.

**Comment by karlglazebrook** [comment]
This is probably right, googling the thing it seems it might even be a temporary apple bug.  I used the flag when building PDL as the messages were plain annoying and everything seems to test just fine.

Karl
