### ISSUE TITLE
Not be able to see texts on the xgterm as they are small

### ISSUE THREAD

**Issue by Lokhamb** [iraf-community/iraf#198]
If I type xgterm on the linux terminal it gives a message **xgterm:  unable to open font "lucidasanstypewriter-18", trying "fixed"....**
and the xgterm opens with small letters it is very very hard to make out. I have a 3.2k display on my laptop....[](url)
![Screenshot from 2021-10-16 19-25-51](https://user-images.githubusercontent.com/92636426/137590202-6627decf-8f25-4bf2-ae4a-f7282094c758.png)
![Screenshot from 2021-10-16 19-26-03](https://user-images.githubusercontent.com/92636426/137590204-62c40d18-1370-493c-a171-632de994c67e.png)

**Comment by olebole** [comment]
You could try to install the package `xfonts-100dpi`, which should contain this font.
