### ISSUE TITLE
Warunatharanga 

### ISSUE THREAD

**Issue by Warunatharanga** [iraf-community/iraf#213]
https://github.com/iraf-community/iraf/blob/9590f45760a4791f3305407fb51c87f1282b32be/doc/notes.v212#L1065-L1075

**Comment by olebole** [comment]
What exactly do you mean here? The issue you mentioned is fixed in 2.17 by [iraf-v216#62](https://iraf-community.github.io/iraf-v216/issues/62).

**Comment by olebole** [comment]
I am closing this one now. If you feel that there is an issue to discuss or to solve, please re-open and specify the issue.
