### ISSUE TITLE
run_tests errors and warning on a Raspberry Pi 4

### ISSUE THREAD

**Issue by steelewool** [iraf-community/iraf#216]
**Describe the bug**

./tests/run_tests failures

**To Reproduce**
Steps to reproduce the behavior.

 1. Do a git clone on this repository
 2. Build the system.
 3. Execute run_tests

Here are my notes:

Just checked out the latest version of iraf from the iraf-community/iraf repository.
After execting the make and make system ... from the installation instructions I got
errors in run_tests.

I'm running on a Raspberry Pi 4 that has a 128 gigabyte SD card so there is plenty of disk space.
In my environment I have done an installation of pyraf using 'apt-get install'. Since
run_tests is using the local copy I would not think there was any side effects of having those
installed.

I am curious if others installing on a Raspberry Pi have seen other issues.

The command and output:
```
$ ./test/run_tests 
ecl.e: README.md 
ecl.e: files.md ......
ecl.e: images.imcoords.md ...........
ecl.e: images.imfilter.md ..............
ecl.e: images.imfit.md ...
ecl.e: images.imgeom.md ........
ecl.e: images.immatch.md ..
ecl.e: lists.md .......
ecl.e: noao.astutil.md ........
ecl.e: noao.digiphot.photcal.md .
ecl.e: numerical-recipes.md ..........
ecl.e: programming.md ............
ecl.e: test-syntax.md ...xsa
ecl.e: testproc.md .F.......................
ecl.e: utilities.nttools.md ..............
Test summary:       1 failed
    123 passed
      2 skipped
      1 xfailed

=================== Failure in testproc.md:57 with ecl.e ===================

Expected
========
cl> digiphot
di> ?
apphot   daophot  photcal  ptools
di> bye
cl> ?
dataio      images      lists       obsolete    proto       system
dbms        language    noao        plot        softools    utilities

Output
======
cl> digiphot
di> ?
      apphot   daophot  photcal  ptools   
di> bye
cl> ?
      dataio      language    noao        plot        softools    utilities
      images      lists       obsolete    proto       system      

Diff
====
@@ -3,5 +3,5 @@
 apphot   daophot  photcal  ptools
 di> bye
 cl> ?
-dataio      images      lists       obsolete    proto       system
-dbms        language    noao        plot        softools    utilities
+      dataio      language    noao        plot        softools    utilities
+      images      lists       obsolete    proto       system    
```

**Expected behavior**

No errors from run_tests

**System details:**

cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

 - Versions of all additionally involved software, i.e. , PyRAF, sptable,

2.1.15 version of pyraf is installed

**Comment by olebole** [comment]
I guess that your source is somehow mixed up. Can you make sure that your repository is an unchanged clone of the current version, or of v2.17? Especially please have a look for these lines in `test/testproc.md`: https://github.com/iraf-community/iraf/blob/268c8804f93d07034f03dafbe5472c7b95865f30/test/testproc.md?plain=1#L55-L64
The last line here should ***not*** contain "dbms", otherwise your source is somehow wrong.
If that is the case I suspect that there is an interference with another IRAF installation, for example the one that is part of Raspbian.
BTW, what is the reason that you want to install IRAF from source instead of using the "iraf" package from Raspbian?

**Comment by steelewool** [comment]
I did a clean clone operation yesterday and then built things. Getting some unexpected interaction between the installed version and the built version could be this issue. When you or others run the code on a Pi without having installed the raspian version then I suspect the problem is mine alone and the issue should be closed.

Why --- I always like the idea of using the latest software and the version on the Pi is 2.16.1 built in 2018. But, if that version is sufficiently close to the 2.17 version you have in the repository I might go back to that one. Also, since I've retried I'm hoping to have more time to work on my astronomy and related software. The thought that I might contribute something positive to IRAF would be great.

**Comment by olebole** [comment]
The changes of the new 2.17 are minor; see the [release notes](https://github.com/iraf-community/iraf/releases/tag/v2.17). And I am pretty sure this is due to the pre-installed version, since the code that you have shown is not in version 2.17.
