### ISSUE TITLE
Issue using cursor on graphics window on Macbook

### ISSUE THREAD

**Issue by carys-evans** [iraf-community/iraf#217]
**Describe the bug**
I am having an issue using the cursor on the graphics window on a Mac. It seems to work variably, so sometimes it's fine, but sometimes it gets stuck at won't move once it's on the graphics window. I am using iraf in conjunction with this pipeline:
https://github.com/svalenti/pessto/tree/python3

I have also posted the issue to the pipeline, but was directed to post it here too in case you have any suggestions.

A video demonstrating the issue can be found here:
https://cf-my.sharepoint.com/:f:/g/personal/evanscr8_cardiff_ac_uk/Etzklvf_5VZAvQbcDMKOgZEBY2UVQgzhUqhvObBS3PRulg?e=XywCdF

Everything else seems to run smoothly, I just am not able to complete the interactive steps that require the use of the cursor.

**System details:**
 - OS: macOS Monterey 12.2
 - Version: 2.17

**Comment by olebole** [comment]
It is not helpful to repeated posts for the same issue. Your original issue was moved to https://github.com/iraf-community/x11iraf/issues/49, since it is a xgterm resp. x11iraf issue.

**Comment by carys-evans** [comment]
My apologies! I hadn't realised it had been moved - I thought it hadn't posted when I came back to check for an update
