### ISSUE TITLE
When giving @file[N] with a MEF fits as input, the index is not parsed correctly.

### ISSUE THREAD

**Issue by WildPenquin** [iraf-community/iraf#235]
HI,

I'm using the community release on Ubuntu 22.04.

I have FITS files with many headers (MEF files). One can specify which extension to use inside the fits file correctly by specifying it inside the list (@file). For example a file (named `file`) with this contend:

```
file1.fits[1]
file2.fits[1]
.
.
.
```
Will work - giving @file for input, to, say, zerocombine (with epar).

However, is is very useful, and it used to work so that  one would *not* have to specify the index in the file list for each file. Instead, to reproduce the bug, give a parameted `@file[N]` where N is the (same) header index to be used for all files in `@file` as input to a task

This is a regression, as this seems to work with older versions of IRAF.

While this can be worked around by giving the index in the input `@file`, it is a bit cumbersome. In addition to needing to add the index for each file in the list, in case the task creates many new fits files, (flatcombine etx.) one needs to create a different list for input and output files, as the latter can not have the index, and also the automatic globbing in the output field can not be used (i.e. input=@file[1], output=b@file does not work - instead a separate output list is needed).

**To Reproduce**

 1. Have MEF fits files handy. Create a `file` with contents:
```
file1.fits
file2.fits
file3.fits
.
.
.
```
 2. Use `epar zerocombine` (or some other task instead of zerocombine which can take many fits images as input), set input as `@file[1] `(or any other index suitable for your MEF files)
 3. Run the task by typing `:go`
 4. Observe an error with the form:
```
ERROR: Cannot open file (file%%)
  "pclip=pclip, grow=0)"
     line 47: ccdred$zerocombine.cl
     called as: `zerocombine (mode=h)'
ccdred> 
```
**Expected behavior**
The task should finish correctly, with the MEF fits files listed in `file`, with index [1] (or [N], if you chose some other N).

This seems to be a regression, as this does work in older IRAF.

**System details:**
Ubuntu 22.04
Community IRAF V2.17

**Comment by olebole** [comment]
I can confirm this; also that it worked with 2.16.1 (and cl).

**Comment by olebole** [comment]
I found the cause: During removal of the VO subsystem ([iraf-v216#93](https://iraf-community.github.io/iraf-v216/issues/93)), the flags that select the new extended image-open procedure were accidentally removed as well.
You can fix this by adding these lines to `unix/hlib/zzsetenv.def`:
```sh
set	use_vo		= yes 
set	use_new_imt	= yes 
```
This will switch to the extended image-open procedure that allows to specify the MEF extension.

I am preparing a Pull Request that unconditionally switches to the new procedure, which would make these lines unneccessary.

**Comment by WildPenquin** [comment]
Hi,

Forgot to comment here but it does indeed work now, thanks!
