### ISSUE TITLE
X11IRAF installation on macOS m1 ventura 13.0.1

### ISSUE THREAD

**Issue by anstockton** [iraf-community/iraf#260]
### Discussed in https://github.com/orgs/iraf-community/discussions/239

<div type='discussions-op-text'>

<sup>Originally posted by **RMnaorch** November 15, 2022</sup>
Hello,
I am installed IRAF follow instructions from the [page](https://iraf-community.github.io/install.html),and there were no proplems.
Installation is done on Macbook pro (13.3-inch, M1, 2020) macOS Ventura version 13.01

However, when I tried installing X11IRAF ,on the step $ make  , and I got the following error:
```
- /Library/Developer/CommandLineTools/usr/bin/make -C obm
cc -I/usr/include/tcl -I/usr/X11/include   -c -o Obm.o Obm.c
cc -I/usr/include/tcl -I/usr/X11/include   -c -o client.o client.c
client.c:137:53: warning: passing 'char ***' to parameter of type 'const char ***' discards qualifiers in nested pointer types [-Wincompatible-pointer-types-discards-qualifiers]
literal:    if (Tcl_SplitList (tcl, command, &argc, &argvp) == TCL_OK) {
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/tclDecls.h:1453:21: note: passing argument to parameter 'argvPtr' here
                                CONST84 char ***argvPtr);
...
...
2 warnings generated.
cc -I../obm -I/usr/include/tcl -I/usr/X11/include   -c -o zscale.o zscale.c
cc -L/usr/X11/lib -o ximtool eps.o fitsio.o gifio.o iis.o irafio.o ism.o ism_wcspix.o load.o logo.o print.o quant.o rasio.o raster.o save.o tiffio.o util.o ximclient.o ximtool.o zscale.o \
	    -L../obm -lobm \
	    -lXpm -ltcl -lXaw3d -lXmu -lXt -lXext -lX11 -lncurses -lm
cd clients && mkpkg || true
/bin/sh: mkpkg: command not found
```
Does anyone know on how to solve this?
Thanks 
</div>

**Comment by anstockton** [comment]
I am trying to install IRAF 2.17 on a MacBook Air M! running Monterey 12.6.3. Everything seemed to go fine until I got to the "make sysgen 2>&1 | tee build.log" command, where I got some sort of bus error, as follows:

macbook-air:iraf-2.17 stockton$ make sysgen 2>&1 | tee build.log
Building the IRAF v2.16 software tree
 
Tue Feb 28 21:39:28 HST 2023
 
(util/mksysgen)
Clean 'macos64' host directories ....
Clean src directories ....
Clean 'macos64' bin directories ....
Cleaning spool files ....
+ set -e
+ sh -x setarch.sh
++ ls -d bin
+ '[' bin = bin ']'
+ rm -rf bin
+ ln -s bin.macos64 bin
+ echo '----------------------- OS -----------------------------'
----------------------- OS -----------------------------
+ echo +
+
+ echo +
+
+ cd os
+ sh -x mkpkg.sh
+ set -e
+ echo '--------------------- OS ----------------------'
--------------------- OS ----------------------
+ gcc -c -g -Wall -O2 -I/Users/stockton/niraf/iraf-2.17/include -DNOVOS -Wall zsvjmp.S gmttolst.c irafpath.c prwait.c zalloc.c zawset.c zcall.c zdojmp.c zfacss.c zfaloc.c zfchdr.c zfdele.c zfgcwd.c zfinfo.c zfiobf.c zfioks.c zfiolp.c zfiomt.c zfiond.c zfiopl.c zfiopr.c zfiosf.c zfiotx.c zfioty.c zflink.c zfmkcp.c zfmkdr.c zfnbrk.c zfpath.c zfpoll.c zfprot.c zfrmdr.c zfrnam.c zfsubd.c zfunc.c zfutim.c zfxdir.c zgcmdl.c zghost.c zglobl.c zgmtco.c zgtenv.c zgtime.c zgtpid.c zintpr.c zlocpr.c zlocva.c zmain.c zmaloc.c zmfree.c zopdir.c zopdpr.c zoscmd.c zpanic.c zraloc.c zshlib.c zttyio.c zwmsec.c zxwhen.c zzdbg.c zzepro.c zzexit.c zzpstr.c zzsetk.c zzstrt.c alloc.c getproc.c
mkpkg.sh: line 10: 21408 Bus error: 10           $CC -c $HSI_CF -Wall zsvjmp.S gmttolst.c irafpath.c prwait.c z*.c alloc.c getproc.c
make: *** [sysgen] Error 138

Can anyone tell me what the problem is likely to be? I would like to get IRAF running on this computer in order to finish up a project started some time ago on an older one.

(BTW, I do wonder about the bit about "Building the IRAF v2.16 software tree"; I notice that the makefile that comes with 2.17 distribution still gives the version as 2.16.)

**Comment by olebole** [comment]
A C compiler should never crash; if it happens it is most probably either a bug of the C compiler or a problem of the hardware. So, first question would be to check that you use the default C compiler as "gcc". I would recommend then just to repeat the make process and see whether it crashes on the same place. If yes, I would try to run the compile command by hand and see if it still crashes reproducibly, followed by shortening the command (using less input files) until the bus error disappears. This way I would try to find out which file causes it.

**Comment by anstockton** [comment]
Thanks; OK, I found that /Applications/Xcode/Contents/Developer/usr/bin/ was not in $PATH, so gcc was not reachable. I had assumed that installing Xcode would take care of this sort of thing. Once I added this path, the compilation seemed to go OK.
