### ISSUE TITLE
IRAF on Cygwin

### ISSUE THREAD

**Issue by arantxax** [iraf-community/iraf#68]
Good evening Ole and collaborators,

I was reading the tutorials to understand how could I use IRAF in a Windows system and I found these forum: http://www.iac.es/sieinvens/siepedia/pmwiki.php?n=HOWTOs.IrafCygwin

I followed all the instructions and I'm proud of myself, because all the steps went sucessfully. But I don't know what to do next. I currently have installed IRAF, but how can I use Cygwin to actually runs it?
The command "mkiraf" or "cl" doesn't actually run IRAF.

I was reading also other foruns here, like this:

04/17/2015 10:18PM (Read 4409 times) |  
Hi all,I'm installing IRAF under Cygwin using the following guide http://www.iac.es/sieinvens/siepedia/pmwiki.php?n=HOWTOs.IrafCygwin After getting stuck on 'mkiraf' for a while I finally got it to work.

I would like to know how he did to actually run IRAF. I'm a total newbie in informatics and also in IRAF.

**Comment by olebole** [comment]
I must say that I have no experiences with cygwin at all, and almost none with MS Windows.
However, the cygwin port of IRAF is rather old and outdated (IRAF 2.14 came out in 2008). If you want to run IRAF on Windows, I would rather recommend to [install the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10), choose Ubuntu 18.04 there, and then just do a
```
$ sudo apt install iraf
```
on the command line. This gives you the newest IRAF version for Ubuntu, which you can then start with
```
$ irafcl
```
You can also install and use PyRAF (`$ sudo apt install python3-pyraf`).

Therefore, I don't see a big need in a cygwin port anymore. However, if there are volunteers to step in and maintain this, I'd be happy to help. It is probably just adding the "cygwin" name here and there.

**Comment by steelewool** [comment]
I'm currently using the latest version IRAF from this repository. I'm running Oracle VirtualBox Version 5.20 r 118431 on my Windows 10 machine. The "uname -all" on my linux looks like:

uname --all
Linux steele 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

But if I were starting over getting the latest Ubuntu version on the latest version of Vitual Box would make the most sense.

The version of IRAF that lives in the iraf.net repositories does not work, for me at least, on my Linux box. And it isn't even close on my Raspberry Pi. (I will admit that the pi is very slow and is really more experimental. - But I think it is cool that IRAF does run on it.) The short story here is that I would begin by cloning/forking the version of IRAF that lives in this repository and then moving forward from there.

**Comment by dgzmr** [comment]
Hello @olebole, your answer was very useful since I just couldn't get iraf to work on Ubuntu. But I ran into a problem trying to run the task splot in iraf using WSL, it returns ERROR: Terminal does not support vector graphics. From what I understand, what may be missing is xgterm but I think this won't work on WSL. Do you have a way to make this work?? Thanks!

**Comment by olebole** [comment]
xgterm is not included in Ubuntu because of licensing issues and its code quality. But you still have the options to either use the standard "xterm", or Pyraf (python3-pyraf); both offer the required emulation.
Note however, that on Windows you also need to install an X server.

**Comment by dgzmr** [comment]
@olebole hey! I ended up installing iraf using     
    $sudo apt install iraf 
on Ubuntu and then installing xterm separately. But now I can't find a way to install the package stsdas.
Someone told me that by installing iraf the way described here https://github.com/iraf-community/iraf/blob/master/INSTALL.md it came with stsdas but when I install it that way after running the command mkiraf and cl it returns an error saying the binary ecl is not found. Could you help me out?

**Comment by dgzmr** [comment]
I read a comment in another issue where you said STSDAS is not available due to licensing issues. Is that right?

**Comment by olebole** [comment]
STSDAS is a separate package that was distributed by STScI. It was never part of the IRAF source code, and so is not installed when following `INSTALL.md`. In Debian, it is not included due to licensing issues, and it will not work in Windows since it is 32 bit only. It will not compile properly with 64 bit (which would be required for WIndows). Also, the sources are no longer available.

**Comment by dgzmr** [comment]
@olebole well, thanks for clarifying these things to me. I will keep trying to install IRAF with STSDAS on Ubuntu hahahah.

**Comment by olebole** [comment]
As there are no plans to support Cygwin, I am closing this.
