### ISSUE TITLE
Problem with installation on Fedora 30 beta

### ISSUE THREAD

**Issue by wuqso** [iraf-community/iraf#83]
I downloaded the source code and tried to installed it on my Fedora 30 (beta) system. I ran the installation script as root:

$ sudo ./install

The errors are as follows:

========================================================================
=========================  Begin Installation  =========================
========================================================================

Checking for existing commands directory...                    [  OK  ]

                             Editing Paths
                             -------------
[  OK  ]
Editing iraf/imdir/cache paths into system files ...           [ FAIL ]
   ***  File mkiraf.sh not found.
   ***  File cl.sh not found.
   ***  File ecl.sh not found.
   ***  File setup.sh not found.
   ***  File setup.csh not found.
Setting mode for $imdir to 0777                                [  OK  ]
Checking cache permissions ...                                 [  OK  ]

                         Creating File Links
                         -------------------
Checking for /iraf symlink ...                                 ln: failed to create symbolic link '/iraf' -> '': No such file or directory
[ FAIL ]
Checking /usr/include directory ...                            [  OK  ]
Creating <iraf.h> symlink ...                                  [ FAIL ]
Creating iraf command links in local bin dir ...               [  OK  ]
Marking system update time hlib$utime ...                      touch: cannot touch '/usr/local/iraf/unix/hlib/utime': No such file or directory
[  OK  ]

                    Creating Graphics Device Files
                    ------------------------------
Checking /usr/local/lib directory ...                          [  OK  ]
Creating /usr/local/lib/imtoolrc link ...                      [ FAIL ]
Creating X11IRAF links ...                                     [  OK  ]

========================================================================
=================  Installation Completed With Errors  =================
========================================================================

What's the problem?

**Comment by lupinix** [comment]
I'm currently reworking RPM packages for Fedora in COPR (updating to the latest snapshot), you'll find it here soon (current builds not yet up to date): https://copr.fedorainfracloud.org/coprs/lupinix/IRAF-Community/

**Comment by wuqso** [comment]
Dear Christian,


Thank you for your email. I visited the website and downloaded the repo file. Then I was able to install IRAF on my computer. It is updated to 2018.06. I didn't find X11iraf and I guess the default terminal is xterm when using IRAF. There is one problem. The xterm window and the fonts therein are very small on the high DPI screen of my laptop. Even I changed the font size into Huge within the xterm, the problem remained. How can I do?



Best,
Jianghua


-----原始邮件-----
发件人:"Christian Dersch" <notifications@github.com>
发送时间:2019-04-26 22:34:43 (星期五)
收件人: iraf-community/iraf <iraf@noreply.github.com>
抄送: wuqso <jhwu@bnu.edu.cn>, Author <author@noreply.github.com>
主题: [SPAM] Re: [iraf-community/iraf] Problem with installation on Fedora 30 beta (#83)



I'm currently reworking RPM packages for Fedora in COPR (updating to the latest snapshot), you'll find it here soon (current builds not yet up to date): https://copr.fedorainfracloud.org/coprs/lupinix/IRAF-Community/

**Comment by olebole** [comment]
@wuqso
>     $ sudo ./install
>     [...]
>     Editing iraf/imdir/cache paths into system files ... [ FAIL ]
>     *** File mkiraf.sh not found.

Can you tell under which base directory you tried to install IRAF? It may have problems with spaces or non-ASCII chars.

**Comment by wuqso** [comment]
Thank you for your email. I tried to install iraf into /usr/local/iraf by using command 'sudo ./install'. The image directory is /usr/local/iraf/imdirs and the cache directory is /usr/local/iraf/cache. The directory of /usr/local is on a separate partition and has free spaces of 3.5 G.


-----原始邮件-----
发件人:"Ole Streicher" <notifications@github.com>
发送时间:2019-04-27 03:40:53 (星期六)
收件人: iraf-community/iraf <iraf@noreply.github.com>
抄送: wuqso <jhwu@bnu.edu.cn>, Mention <mention@noreply.github.com>
主题: Re: [iraf-community/iraf] Problem with installation on Fedora 30 beta (#83)



@wuqso

$ sudo ./install
[...]
Editing iraf/imdir/cache paths into system files ... [ FAIL ]
*** File mkiraf.sh not found.


Can you tell under which base directory you tried to install IRAF? It may have problems with spaces or non-ASCII chars.

**Comment by olebole** [comment]
Hmm, at least I can't reproduce this under Debian Stretch. Did you really copy everything into `/usr/local/iraf/`? Specifically, do the files `mkiraf.sh`, `cl.sh`, `ecl.sh`, `setup.sh` and `setup.csh` exist in the `unix/hlib/` subdirectory?

**Comment by wuqso** [comment]
Yes, I copied everything into /usr/local/iraf/ (I didn't see any instruction on the copy of files in this version of IRAF distribution) and made a directory /iraf (if this directory was not made, the installation would claim error). Then IRAF can be installed with no error. But the commands cl and ecl cannot be run. The installation required a directory of /iraf, but after the installation was completed, I checked and found an empty /iraf. The x11iraf also has some errors in installation. I'm wondering whether the iraf community has had any test on the release of IRAF.


-----原始邮件-----
发件人:"Ole Streicher" <notifications@github.com>
发送时间:2019-04-27 20:27:33 (星期六)
收件人: iraf-community/iraf <iraf@noreply.github.com>
抄送: wuqso <jhwu@bnu.edu.cn>, Mention <mention@noreply.github.com>
主题: Re: [iraf-community/iraf] Problem with installation on Fedora 30 beta (#83)



Hmm, at least I can't reproduce this under Debian Stretch. Did you really copy everything into /usr/local/iraf/? Specifically, do the files mkiraf.sh, cl.sh, ecl.sh, setup.sh and setup.csh exist in the unix/hlib/ subdirectory?

**Comment by olebole** [comment]
> [...] and made a directory /iraf (if this directory was not made, the installation would claim error). Then IRAF can be installed with no error

Does this mean that this error appears if you don't have an `/iraf` subdirectory, but not if you have it?

```
Editing iraf/imdir/cache paths into system files ... [ FAIL ]
*** File mkiraf.sh not found.
*** File cl.sh not found.
*** File ecl.sh not found.
*** File setup.sh not found.
*** File setup.csh not found.
```

> But the commands cl and ecl cannot be run.

Could you attach the full build log to check? 

> I'm wondering whether the iraf community has had any test on the release of IRAF.

https://travis-ci.com/iraf-community/iraf/builds

**Comment by olebole** [comment]
I think I found out what is wrong there: The `./install` script does not copy anything to a new location. It is meant to run **after** you unpacked (or copied/moved) the files in a (new) location. So, the first question of `./install` is misleading and should always answered with the default; otherwise the installation will fail.

I have no idea why this is so; maybe you ask @mjfitzpatrick (the original author) for the rationale. I will change this here.
