### ISSUE TITLE
Tab Auto-completion & Up-arrow History Search

### ISSUE THREAD

**Issue by bijiaqing** [iraf-community/iraf#92]
Hi,

Does this version of IRAF support tab auto-completion and up-arrow history search? It does not work on my Fedora 29 environment. I am very new to this software and I don't know if it simply does not support those or I need to install some more packages to achieve those features. 

Any ideas on that?

Thanks,
Jiaqing

**Comment by olebole** [comment]
Up-down arrow history works within the same session (the history is not saved on disk).  Tab completion does not work. It is not planned to add saving history of tab completion, but patches are welcome here.

**Comment by bijiaqing** [comment]
Hi Ole,

Thanks for the reply.
Now I know why I couldn't have tab-completion.
But I am still struggling with the history commands as whenever I press the
arrow buttons it will only show the raw inputs (i.e. "^[[A", "^[[B",
"^[[C", and "^[[D" for up, down, right, and left arrow).
The left/right arrow does not move the cursor and the up/down arrow does
not show the history.
Is that because I am using Fedora or because of my environment setups?

Thanks,
Jiaqing

Ole Streicher <notifications@github.com> 于2019年10月3日周四 上午6:31写道：

**Comment by olebole** [comment]
That looks more like a problem of your environment; you should specifically check the `TERM` environment variable. And maybe go through the [readline (3)](http://manpages.org/readline/3) manpage.

**Comment by olebole** [comment]
It ofcourse also depends on whether you use `cl` or `ecl` -- only the latter has the readline builtin.

**Comment by bijiaqing** [comment]
That's it. For a long time I have only known to use cl to launch iraf.
If I use ecl to launch iraf I will not only have arrows work but also have
tab-completion work.
Thank you so much for your time!

Ole Streicher <notifications@github.com> 于2019年10月4日周五 上午11:33写道：
