### ISSUE TITLE
ctio fft1d causes endless loop

### ISSUE THREAD

**Issue by MarcosIAG** [iraf-community/iraf#94]
Fresh install of IRAF and external package CTIO. 
Main IRAF make sysgen and CTIO mkpkg on ubuntu 16.04  (AMD 64). 
MACH and IRAFARCH = linux64

fft1d enters an endless cpu busy state.

**Comment by olebole** [comment]
Although CTIO is involved, this seems to be an IRAF core problem -- it finally calls `sys/vops/fftx.f` or `sys/vops/fftr.f` for the actual FFT. Differently from the other FFT routines in IRAF, this one was [not marked as originated by *Numerical Recipes*](https://iraf-community.github.io/iraf-v216/license-problems) and therefore remained original (and not replaced by ffpack in 934ea800addef59847922f060c9955fe7cc01968).
Could you provide a small example file and the exact CL commands that lead to the endless loop?
Do you know whether it worked for other versions (like the original 2.16.1, or under 32bit)?

**Comment by MarcosIAG** [comment]
Hi Ole,

That is true, those fft utilities based on complex vops are much older than
Numerical Recipes.

The ctio fft1d task works fine in current stsci astroconda 2.16 stack
installation (a 2013 update).

Please find attached a sample spectrum and the ftt1d pars that fail (but
work on conda distribution).

many thanks and regards,

Marcos


--------------------------------------------------------
Marcos P. Diaz

prof. livre-docente

Departamento de Astronomia
Instituto de Astronomia, Geofísica e Ciências Atmosféricas
Universidade de São Paulo

Rua do Matão, 1226, Butanta
05508-900, São Paulo, SP, Brasil
e-mail: marcos@astro.iag.usp.br
url: astroweb.iag.usp.br/~marcos <http://astroweb.iag.usp.br/%7Emarcos>
voice: 55-11-30912720 skype: marpdiaz fax:55-11-30912860
----------------------------------------------------------

**Comment by olebole** [comment]
Test files:

[testfiles.tar.gz](https://github.com/iraf-community/iraf/files/3754108/testfiles.tar.gz)

**Comment by olebole** [comment]
OK, first debugging gives that `fftx.f` is really buggy. The variable `l` is defined as `l(15)` (implicitly as `real`):  https://github.com/iraf-community/iraf/blob/c2bb53e951664c62f08096138e0db02bd3d31ac4/sys/vops/fftx.f#L20

However, then there is a loop over the index until 31: https://github.com/iraf-community/iraf/blob/c2bb53e951664c62f08096138e0db02bd3d31ac4/sys/vops/fftx.f#L84-L87

This just can't work at all, and did never work, and I wonder how this passed any test at NOAO. It just randomly overwrites the stack, or wherever the `l` array is placed. Originally, the loop went only as `do 110 j=1,15`, but was [extended to 31 with version 2.14 (2006)](https://github.com/iraf-community/iraf/commit/295035060d3da4ebac70c2f967add166b84a33bc#diff-dc2af7a990632f299d70fed23e42d6f0), with this (supposed) changelog entry: https://github.com/iraf-community/iraf/blob/c2bb53e951664c62f08096138e0db02bd3d31ac4/doc/notes.v212#L1913-L1916

One may guess that the second change in this diff was done on error: who knows?
In principle, one could have two ways to "fix" this:
 1. Just revert the change for this loop and hope that everything is OK
 2. Try to replace the `fftx.f` and `fftr.f` code with the libfftw, which is nowalso used elsewhere in IRAF. I would suppose this would be the clean solution.
